### ISSUE TITLE
Refactor - V2V to BSIS

### ISSUE THREAD

**Issue by danfuterman** [jembi/bsis#295]

**Comment by timler** [comment]
I did a little research on what was required to perform the refactoring of V2V to BSIS:

 * for the actual rename of the database, the best approach is to shut down the BSIS server(s) and dump the existing v2v_new database. Then create a new BSIS database and import the v2v_new dump. This is considered a safe approach. The RENAME_DATABASE command provided by MySQL has been removed. See: https://dev.mysql.com/doc/refman/5.1/en/rename-database.html
 * for the properties files:
  * liquibase.properties file - the db details need to be changed in order to run liquibase changesets (which appears to only be during the build - not on application startup)
  * persistence.xml and persistenceTest.xml files - I suggest that we remove the properties relating to the database as they are not used (the datasource is set up in v2v-servlet.xml file)
  * database.properties - this is where the database settings for the application are
  * v2v.properties - I'd suggest merging this with database properties or deleting it if it's not used. It just adds to the database setting confusion.
 * in the code:
  * V2VUserDetails: custom implementation of Spring Security UserDetails (can just be renamed)
  * LoginUserService: custom implementation of Spring Security UserDetailsService that references V2VUserDetails
  * EntitySaveListener: references to V2VUserDetails
  * V2VLogLevel: custom log level for the app (can just be renamed)
  * LoggerUtil: uses the V2VLogLevel
  * UtilController: loading of the v2v.properties file & use of the V2VUserDetails
  * AdminController: references to the v2v.properties keys regarding database backup.
  * EmailReceiverService: commented out code, but only a couple references
  * SchemaGenerator: comment
  * ProductControllerTest, RoleControllerTest, UserControllerTest: references to the v2v_servlet.xml file
  * DonorRepositoryTest and DonorCommunicationsRepositoryTest: references to the v2v_servlet.xml and V2VUserDetails.

Aside from the hassle having to manually rename the database, I think this is a straightforward refactoring exercise.

**Comment by danfuterman** [comment]
Thanks @timler, this looks great. 
And so I don't forget - the puppet scripts should be updated to refactor references to the `v2v_new` database.

**Comment by timler** [comment]
Done all the refactoring except for the actual database rename. See branch: 295_Refactor_V2V_to_BSIS

I will now look at the Lesotho data before completing this rename task.

**Comment by timler** [comment]
Script to rename the database from v2v_new to bsis.

```bash
#!/bin/bash

read -sp "Enter mysql username: " sqluser
echo ""
read -sp "Enter mysql password: " sqlpasswd

echo ""
echo "Backing up v2v_new database ..."
mysqldump -u $sqluser -p$sqlpasswd v2v_new > v2v_new_final.sql

echo ""
echo "Creating bsis database ..."
mysql -u $sqluser -p$sqlpasswd -e 'create database bsis';

echo ""
echo "Restoring v2v_new backup ..."
mysql -u $sqluser -p$sqlpasswd bsis < v2v_new_final.sql

echo ""
echo "Deleting old v2v_new database ..."
mysql -u $sqluser -p$sqlpasswd -e 'drop database v2v_new';
```
