### ISSUE TITLE
Incorrect/Non-updated display of blood type status in test batch view

### ISSUE THREAD

**Issue by danfuterman** [jembi/bsis#458]
There is a bug in the Serology testing whereby after confirming ambiguous blood types, the view isn't updated and displays previous state of blood type - Instead of Complete Match it's still ambiguous, upon refresh the correct status values are displayed 

more details to follow 

//1 - Initial Recording
//2 - Confirmatory Recording
//3 - Display after Confirmatory Recording - incorrect view - should be complete matches
//4 - After Refresh (F5) the correct view is displayed

**Comment by timler** [comment]
There are two parts to this problem.

One is easy to fix and caused as a result of the fix for https://github.com/jembi/bsis-frontend/pull/332. This was caused when doing blood serology outcome confirmations - the test batch overview page was loaded too early - after the test results were saved but before all the Donor, Donation and statuses were updated.

See attached PR for bsis-frontend. https://github.com/jembi/bsis-frontend/issues/338

The second is less easy to fix. This is a problem when modifying test outcomes (Record Blood Group Serology Results) - if the status should change as a result of the test outcomes changing then the table is not updated consistantly. At the moment it depends on the status of the donations - for example if there is a donation that cannot be released the blood testing rules engine is not executed for subsequent donations. Thus some donations will have an updated status while others will not (this is done while determining permissions on the test batch). When the test results are saved the BloodTestsUpdatedEventListener is used to update the status but because this event runs in a separate thread when the save test result endpoint returns it might not have updated the status in time for the read when the page is reloaded.

My recommendation is to replace the BloodTestsUpdatedEvent and BloodTestsUpdatedEventListener with a simple service.

**Comment by timler** [comment]
I just added the PR for the second part of the fix (to do when you change the blood typing initial test outcomes). The problem wasn't just caused by the BloodTestsUpdatedEventListener (which ran the updates to the Donation in a separate thread), but also by the code in the blood test rules engine which compares the blood ABO/Rh for the Donor with the ABO/Rh for the Donation. The problem is that the Donation ABO/Rh is only updated after the rules engine is finished, so it's only on a 2nd execution of the rules engine when the status are correct.
